name: "TESTS"

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  check:
    runs-on: ubuntu-latest

    if: github.event.pull_request.draft == false

    services:
      postgres:
        image: postgres:13.1
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.12

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set Envs
        uses: allenevans/set-env@v2.0.0
        with:
          DB_USER: 'postgres'
          DB_PASSWORD: 'postgres'
          DB_HOST: 'localhost'
          DB_NAME: 'postgres'
          DB_PORT: '5432'

      - name: List Files
        run: ls -al

      - name: Apply Migrations
        run: alembic upgrade head

      - name: Run Tests
        run: pytest tests
